name: grafana
type: python:3.6
disk: 2048

relationships:
    datadb: "influxdata:influxdb"
    confdb: "mysqlconfig:mysql"
    sessdb: "redissession:redis"

mounts:
    'data':
        source: local
        source_path: data
    'conf/provisioning/plugins':
        source: local
        source_path: plugins
    'conf/provisioning/notifiers':
        source: local
        source_path: notifiers
    'conf/provisioning/dashboards':
        source: local
        source_path: dashboards

web:
    upstream:
        socket_family: tcp
        protocol: http
    commands:
        start: "sh ./start.sh"
    locations:
        /:
            root: public

hooks:
    build: "bash ${PLATFORM_APP_DIR}/build.sh"
    deploy: "sh ${PLATFORM_APP_DIR}/deploy.sh"
